[phases.setup]
nixPkgs = ["php83", "php83Extensions.exif", "php83Extensions.gd", "php83Extensions.pdo_mysql", "php83Extensions.pdo_pgsql", "php83Extensions.pdo_sqlite", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "composer_2"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "npm install && npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
